# Generated by Django 3.2.5 on 2022-03-15 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageattachment',
            name='image',
            field=models.ImageField(help_text='Allowed extensions are: png, jpeg, jpg.', upload_to='uploads/contents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])], verbose_name='Image'),
        ),
    ]
