# Generated by Django 3.2.5 on 2022-01-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageattachment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImageAttachments', to='base.content', verbose_name='Content'),
        ),
    ]
