# Generated by Django 3.0.4 on 2020-04-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_course_category_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/categories/', verbose_name='Title Image'),
        ),
    ]
