# Generated by Django 3.0.4 on 2020-04-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
        migrations.AddField(
            model_name='course',
            name='owners',
            field=models.ManyToManyField(related_name='owned_courses', to='base.Profile', verbose_name='Owners'),
        ),
    ]
