# Generated by Django 3.0.4 on 2020-04-08 23:00

from django.db import migrations, models
import django.db.models.deletion
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_course_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('symbol', fontawesome_5.fields.IconField(blank=True, help_text='Symbol to show with this tag (optional)', max_length=60, verbose_name='Symbol')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='base.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='CourseStructureEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=50, verbose_name='Index')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Course', verbose_name='Course')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.Topic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Course Structure Entry',
                'verbose_name_plural': 'Course Structure Entries',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description', blank=True)),
                ('type', models.CharField(max_length=30, verbose_name='Type')),
                ('language', models.CharField(choices=[('de', 'German'), ('en', 'English')], max_length=30, verbose_name='Language')),
                ('readonly', models.BooleanField(default=False, help_text='Can this content be updated?', verbose_name='Readonly')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rendered preview')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='base.Profile', verbose_name='Author')),
                ('tags', models.ManyToManyField(related_name='contents', to='base.Tag', verbose_name='Tags', blank=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='base.Topic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.ManyToManyField(related_name='courses', through='base.CourseStructureEntry', to='base.Topic', verbose_name='Topics', blank=True),
        ),
    ]
