# Generated by Django 3.0.4 on 2020-04-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='public',
            field=models.BooleanField(default=False, help_text="May this content be displayed in courses that don't require registration?", verbose_name='Show in public courses?'),
        ),
    ]
