# Generated by Django 3.0.7 on 2020-12-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accept_privacy_policy',
            field=models.BooleanField(blank=True, default=False, verbose_name='Privacy Policy'),
        ),
    ]
