# Generated by Django 3.0.7 on 2021-01-30 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20210130_2314'),
        ('base', '0010_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.ImageAttachment', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Profile', verbose_name='Rating user'),
        ),
    ]
