# Generated by Django 3.0.7 on 2021-02-12 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210130_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
        ),
    ]
