# Generated by Django 3.0.7 on 2021-02-14 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20210212_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
        ),
    ]
