# Generated by Django 3.0.7 on 2021-02-19 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20210214_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestructureentry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_topic', to='base.Topic', verbose_name='Topic'),
        ),
    ]
