# Generated by Django 3.0.7 on 2021-03-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20210222_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='public',
            field=models.BooleanField(default=False, help_text="This content will be displayed in courses that don't require registration", verbose_name='Show in public courses'),
        ),
        migrations.AlterField(
            model_name='content',
            name='readonly',
            field=models.BooleanField(default=False, help_text="This content shouldn't be edited", verbose_name='Set to Read-Only'),
        ),
        migrations.AlterField(
            model_name='course',
            name='restrict_changes',
            field=models.BooleanField(blank=True, default=False, help_text='This course is restricted and can only be edited by the owners', verbose_name='Edit Restriction'),
        ),
    ]
