# Generated by Django 3.2.5 on 2021-07-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_privacy_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stared_courses',
            field=models.ManyToManyField(blank=True, related_name='staring_users', to='base.Course', verbose_name='Stared courses:'),
        ),
    ]
