# Generated by Django 3.2.18 on 2023-04-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_stared_courses_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Display Name'),
        ),
    ]
