# Generated by Django 3.2.18 on 2023-04-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_fill_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=150, verbose_name='Display Name'),
        ),
    ]
