# Generated by Django 3.2.20 on 2024-02-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_display_name_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='approved',
            field=models.BooleanField(default=False, help_text='This content is approved by a moderator', verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='course',
            name='moderators',
            field=models.ManyToManyField(related_name='moderating_users', to='base.Profile', verbose_name='Moderators'),
        ),
        migrations.AddField(
            model_name='profile',
            name='moderated_courses',
            field=models.ManyToManyField(blank=True, related_name='moderated_courses', to='base.Course', verbose_name='Moderated courses:'),
        ),
    ]
