# Generated by Django 3.2.20 on 2024-01-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_display_name_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='public',
            field=models.BooleanField(default=False, help_text='This course can be accessed by unregistered users ', verbose_name='Show in public courses'),
        ),
    ]
