# Generated by Django 3.2.20 on 2024-02-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_display_name_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='approved',
            field=models.BooleanField(default=False, help_text='This content is approved by a moderator', verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='course',
            name='moderators',
            field=models.ManyToManyField(blank=True, default=None, related_name='moderated_courses', to='base.Profile', verbose_name='Moderators'),
        ),
        migrations.AddField(
            model_name='course',
            name='public',
            field=models.BooleanField(default=False, help_text='This course can be accessed by unregistered users ', verbose_name='Publicly accessible'),
        ),
    ]
