# Generated by Django 3.2.20 on 2024-02-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20240215_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='hidden',
            field=models.BooleanField(default=False, help_text='This content is hidden in the course by a moderator', verbose_name='Hidden'),
        ),
    ]
