# Generated by Django 3.2.20 on 2024-02-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20240201_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='moderated_courses',
        ),
        migrations.AddField(
            model_name='course',
            name='public',
            field=models.BooleanField(default=False, help_text='This course can be accessed by unregistered users ', verbose_name='Publicly accessible'),
        ),
        migrations.AlterField(
            model_name='course',
            name='moderators',
            field=models.ManyToManyField(blank=True, default=None, related_name='moderated_courses', to='base.Profile', verbose_name='Moderators'),
        ),
    ]
