# Generated by Django 3.2.20 on 2024-02-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_course_moderators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='moderated_courses',
        ),
        migrations.AlterField(
            model_name='course',
            name='moderators',
            field=models.ManyToManyField(related_name='moderated_courses', to='base.Profile', verbose_name='Moderators'),
        ),
    ]
