# Generated by Django 3.2.20 on 2024-02-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20240229_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='author_message',
            field=models.TextField(blank=True, help_text='The message from the author', null=True, verbose_name='Author Message'),
        ),
        migrations.AlterField(
            model_name='content',
            name='user_message',
            field=models.TextField(blank=True, help_text='The message from the user', null=True, verbose_name='User Message'),
        ),
    ]
