# Generated by Django 3.2.20 on 2024-02-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_course_moderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='moderators',
            field=models.ManyToManyField(blank=True, default=None, related_name='moderated_courses', to='base.Profile', verbose_name='Moderators'),
        ),
    ]
