# Generated by Django 3.0.7 on 2021-01-02 13:49

import content.mixin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0010_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.Content', verbose_name='Content')),
                ('image', models.ImageField(upload_to='uploads/contents/%Y/%m/%d/', verbose_name='Image Attachment')),
                ('source', models.TextField(verbose_name='Source')),
                ('license', models.CharField(blank=True, max_length=200, verbose_name='License')),
            ],
            options={
                'verbose_name': 'Image Attachment in Content',
                'verbose_name_plural': 'Image Attachments in Content',
            },
        ),
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.Content', verbose_name='Content')),
                ('image', models.ImageField(upload_to='uploads/contents/%Y/%m/%d/', verbose_name='Image')),
                ('source', models.TextField(verbose_name='Source')),
                ('license', models.CharField(blank=True, max_length=200, verbose_name='License')),
            ],
            options={
                'verbose_name': 'Image Content',
                'verbose_name_plural': 'Image Contents',
            },
        ),
        migrations.CreateModel(
            name='Latex',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.Content', verbose_name='Content')),
                ('textfield', models.TextField(verbose_name='Code Body')),
                ('source', models.TextField(verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Latex Content',
                'verbose_name_plural': 'Latex Contents',
            },
        ),
        migrations.CreateModel(
            name='PdfContent',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.Content', verbose_name='Content')),
                ('pdf', models.FileField(upload_to='uploads/contents/%Y/%m/%d/', verbose_name='Pdf')),
                ('source', models.TextField(verbose_name='Source')),
                ('license', models.CharField(blank=True, max_length=200, verbose_name='License')),
            ],
            options={
                'verbose_name': 'Pdf Content',
                'verbose_name_plural': 'Pdf Contents',
            },
            bases=(models.Model, content.mixin.GeneratePreviewMixin),
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.Content', verbose_name='Content')),
                ('textfield', models.TextField(verbose_name='Textfield')),
                ('source', models.TextField(verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Textfield Content',
                'verbose_name_plural': 'Textfield Contents',
            },
        ),
        migrations.CreateModel(
            name='YTVideoContent',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.Content', verbose_name='Content')),
                ('url', models.URLField(verbose_name='Video URL')),
            ],
            options={
                'verbose_name': 'YouTube Video Content',
                'verbose_name_plural': 'YouTube Video Contents',
            },
        ),
    ]
