# Generated by Django 3.0.4 on 2020-04-09 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0007_course_title_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='YTVideoContent',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.Content', verbose_name='Content')),
                ('url', models.URLField(verbose_name='Video URL')),
            ],
            options={
                'verbose_name': 'YouTube Video Content',
                'verbose_name_plural': 'YouTube Video Contents',
            },
        ),
    ]
