# Generated by Django 3.0.4 on 2020-04-09 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_course_title_unique'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.Content', verbose_name='Content')),
                ('image', models.ImageField(upload_to='uploads/contents/%Y/%m/%d/', verbose_name='Image')),
                ('source', models.TextField(verbose_name='Source')),
                ('license', models.CharField(blank=True, max_length=200, verbose_name='Licence')),
            ],
            options={
                'verbose_name': 'Image Content',
                'verbose_name_plural': 'Image Contents',
            },
        ),
    ]
