# Generated by Django 3.0.4 on 2020-06-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontent',
            name='license',
            field=models.CharField(blank=True, max_length=200, verbose_name='License'),
        ),
    ]
