# Generated by Django 3.0.4 on 2020-06-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_favorite'),
        ('content', '0003_license_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFContent',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.Content', verbose_name='Content')),
                ('pdf', models.ImageField(upload_to='uploads/contents/%Y/%m/%d/', verbose_name='pdf')),
                ('source', models.TextField(verbose_name='Source')),
                ('license', models.CharField(blank=True, max_length=200, verbose_name='License')),
            ],
            options={
                'verbose_name': 'Pdf Content',
                'verbose_name_plural': 'Pdf Contents',
            },
        ),
    ]
