# Generated by Django 3.0.4 on 2020-07-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_pdfcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfcontent',
            name='pdf',
            field=models.FileField(upload_to='uploads/contents/%Y/%m/%d/', verbose_name='Pdf'),
        ),
    ]
