# Generated by Django 3.0.7 on 2021-01-30 22:14

import content.mixin
import content.validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_favorite'),
        ('content', '0005_auto_20200729_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latex',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.Content', verbose_name='Content')),
                ('pdf', models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', validators=[content.validator.validate_pdf], verbose_name='PDF')),
                ('textfield', models.TextField(verbose_name='Latex Code')),
                ('source', models.TextField(verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Latex Content',
                'verbose_name_plural': 'Latex Contents',
            },
            bases=(models.Model, content.mixin.GeneratePreviewMixin),
        ),
        migrations.CreateModel(
            name='SingleImageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(verbose_name='Source')),
                ('license', models.CharField(blank=True, max_length=200, verbose_name='License')),
                ('image', models.ImageField(upload_to='uploads/contents/%Y/%m/%d/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Single Image Attachment',
                'verbose_name_plural': 'Single Attachments',
            },
            bases=(models.Model, content.mixin.GeneratePreviewMixin),
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.Content', verbose_name='Content')),
                ('textfield', models.TextField(verbose_name='Text')),
                ('source', models.TextField(verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Textfield Content',
                'verbose_name_plural': 'Textfield Contents',
            },
            bases=(models.Model, content.mixin.GeneratePreviewMixin),
        ),
        migrations.AlterModelOptions(
            name='pdfcontent',
            options={'verbose_name': 'PDF Content', 'verbose_name_plural': 'PDF Contents'},
        ),
        migrations.AlterField(
            model_name='pdfcontent',
            name='pdf',
            field=models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', validators=[content.validator.validate_pdf], verbose_name='PDF'),
        ),
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(blank=True, related_name='images', to='content.SingleImageAttachment', verbose_name='Images')),
            ],
            options={
                'verbose_name': 'Image Attachment',
                'verbose_name_plural': 'Image Attachments',
            },
            bases=(models.Model, content.mixin.GeneratePreviewMixin),
        ),
    ]
