# Generated by Django 3.0.7 on 2021-01-30 22:14

import content.mixin
import content.validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_favorite'),
        ('content', '0005_auto_20200729_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latex',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.Content', verbose_name='Content')),
                ('pdf', models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', validators=[content.validator.Validator.validate_pdf], verbose_name='PDF')),
                ('textfield', models.TextField(verbose_name='LaTeX Code')),
                ('source', models.TextField(verbose_name='Source')),
            ],
            options={
                'verbose_name': 'LaTeX Content',
                'verbose_name_plural': 'LaTeX Contents',
            },
            bases=(models.Model, content.mixin.GeneratePreviewMixin),
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.Content', verbose_name='Content')),
                ('textfield', models.TextField(verbose_name='Text')),
                ('source', models.TextField(verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Textfield Content',
                'verbose_name_plural': 'Textfield Contents',
            },
            bases=(models.Model, content.mixin.GeneratePreviewMixin),
        ),
        migrations.AlterModelOptions(
            name='pdfcontent',
            options={'verbose_name': 'PDF Content', 'verbose_name_plural': 'PDF Contents'},
        ),
        migrations.AlterField(
            model_name='pdfcontent',
            name='pdf',
            field=models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', validators=[content.validator.Validator.validate_pdf], verbose_name='PDF'),
        ),
    ]
