# Generated by Django 3.0.4 on 2020-10-08 10:36
import os

from django.db import migrations
from pdf2image import convert_from_path

from collab_coursebook import settings
from content.models import PdfContent


def generate_preview(obj):
    preview_folder = 'uploads/previews/'
    # Check if Folder exists
    if not os.path.exists(os.path.join(settings.MEDIA_ROOT, preview_folder)):
        os.makedirs(os.path.join(settings.MEDIA_ROOT, preview_folder))
    base_filename = os.path.splitext(os.path.basename(obj.pdf.name))[0] + '.jpg'
    # get images for every page
    pages = convert_from_path(obj.pdf.path, last_page=2)
    # save first page to disk
    pages[0].save(os.path.join(settings.MEDIA_ROOT, preview_folder, base_filename))
    return os.path.join(preview_folder, base_filename)

def update_previews(apps, schema_editor):
    Pdfs = apps.get_model('content', 'PdfContent')
    for pdf in Pdfs.objects.all():
        print(pdf)
        new_preview = generate_preview(pdf)
        pdf.preview.name = new_preview
        pdf.save()

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20200729_1405'),
    ]

    operations = [
        migrations.RunPython(update_previews)
    ]
