# Generated by Django 3.0.7 on 2021-02-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20210130_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleimageattachment',
            options={'verbose_name': 'Single Image Attachment', 'verbose_name_plural': 'Single Image Attachments'},
        ),
    ]
