# Generated by Django 3.0.7 on 2021-01-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_favorite'),
        ('content', '0006_imageattachment_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latex',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.Content', verbose_name='Content')),
                ('textfield', models.TextField(verbose_name='Code Body')),
                ('source', models.TextField(verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Latex Content',
                'verbose_name_plural': 'Latex Contents',
            },
        ),
        migrations.AlterField(
            model_name='textfield',
            name='textfield',
            field=models.TextField(verbose_name='Textfield'),
        ),
    ]
