# Generated by Django 3.0.7 on 2021-03-02 22:52

import content.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20210219_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytvideocontent',
            name='url',
            field=models.URLField(validators=[content.validator.Validator.validate_youtube_url], verbose_name='Video URL'),
        ),
    ]
