# Generated by Django 3.0.7 on 2021-02-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20210219_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageattachment',
            name='content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ImageAttachments', to='base.Content', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
