# Generated by Django 3.0.7 on 2021-01-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20210101_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfield',
            name='source',
            field=models.TextField(default='Local System', verbose_name='Source'),
            preserve_default=False,
        ),
    ]
