# Generated by Django 3.0.7 on 2021-02-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_content_attachment'),
        ('content', '0008_auto_20210219_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageattachment',
            options={'verbose_name': 'Single Image Attachment', 'verbose_name_plural': 'Single Image Attachments'},
        ),
        migrations.RemoveField(
            model_name='imageattachment',
            name='images',
        ),
        migrations.AddField(
            model_name='imageattachment',
            name='content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ImageAttachments', to='base.Content', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageattachment',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/contents/%Y/%m/%d/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageattachment',
            name='license',
            field=models.CharField(blank=True, max_length=200, verbose_name='License'),
        ),
        migrations.AddField(
            model_name='imageattachment',
            name='source',
            field=models.TextField(default=None, verbose_name='Source'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SingleImageAttachment',
        ),
    ]
