# Generated by Django 3.0.7 on 2021-02-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20210226_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageAttachment',
        ),
    ]
