# Generated by Django 3.2.5 on 2021-07-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20210302_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latex',
            name='textfield',
            field=models.TextField(help_text='Please insert only valid LaTeX code. The packages and \\begin{document} and \\end{document} will be inserted automatically.', verbose_name='Latex Code'),
        ),
    ]
