# Generated by Django 3.2.5 on 2021-11-26 14:19

import content.mixin
import content.validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_stared_courses_fix'),
        ('content', '0009_alter_latex_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDFileContent',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.content', verbose_name='Content')),
                ('md', models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', validators=[content.validator.Validator.validate_md], verbose_name='MD File')),
                ('source', models.TextField(verbose_name='Source')),
            ],
            options={
                'verbose_name': 'MD File',
                'verbose_name_plural': 'MD files',
            },
            bases=(models.Model, content.mixin.GeneratePreviewMixin),
        ),
    ]
