# Generated by Django 3.0.7 on 2021-01-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_textfield_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='latex',
            name='pdf',
            field=models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', verbose_name='Pdf'),
        ),
    ]
