# Generated by Django 3.2.5 on 2021-11-28 22:07

import content.mixin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_stared_courses_fix'),
        ('content', '0009_alter_latex_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDContent',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.content', verbose_name='Content')),
                ('md', models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', verbose_name='MD')),
                ('textfield', models.TextField(help_text='Insert your markdown script here:', verbose_name='Markdown Script')),
                ('source', models.TextField(verbose_name='Source')),
            ],
            options={
                'verbose_name': 'MD Content',
                'verbose_name_plural': 'MD Contents',
            },
            bases=(models.Model, content.mixin.GeneratePreviewMixin),
        ),
    ]
