# Generated by Django 3.2.5 on 2022-01-25 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_mdcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytvideocontent',
            name='endTime',
            field=models.PositiveIntegerField(default=0, verbose_name='Video End Time in Seconds'),
        ),
        migrations.AddField(
            model_name='ytvideocontent',
            name='startTime',
            field=models.PositiveIntegerField(default=0, verbose_name='Video Start Time in Seconds'),
        ),
        migrations.AlterField(
            model_name='mdcontent',
            name='md',
            field=models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['md'])], verbose_name='Markdown File'),
        ),
        migrations.AlterField(
            model_name='mdcontent',
            name='textfield',
            field=models.TextField(blank=True, help_text='Insert your Markdown script here:', verbose_name='Markdown Script'),
        ),
    ]
