# Generated by Django 3.0.7 on 2021-01-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_latex_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageattachment',
            name='content',
        ),
        migrations.AddField(
            model_name='imageattachment',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
