# Generated by Django 3.2.5 on 2021-11-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_mdcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdcontent',
            name='html',
            field=models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', verbose_name='HTML'),
        ),
    ]
