# Generated by Django 3.2.5 on 2022-03-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20220125_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytvideocontent',
            name='endTime',
            field=models.CharField(default='0:00', help_text='Type in the time as HH:MM:SS (e.g. 2:05:10, 2:05, 0:50).', max_length=8, verbose_name='Video End Timestamp'),
        ),
        migrations.AlterField(
            model_name='ytvideocontent',
            name='startTime',
            field=models.CharField(default='0:00', help_text='Type in the time as HH:MM:SS (e.g. 2:05:10, 2:05, 0:50).', max_length=8, verbose_name='Video Start Timestamp'),
        ),
    ]
