# Generated by Django 3.0.7 on 2021-01-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20210105_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageattachment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
