# Generated by Django 3.2.5 on 2021-12-01 17:49

import content.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_mdcontent_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdcontent',
            name='md',
            field=models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', validators=[content.validator.Validator.validate_md], verbose_name='Markdown File'),
        ),
        migrations.AlterField(
            model_name='mdcontent',
            name='textfield',
            field=models.TextField(blank=True, help_text='Insert your Markdown script here:', verbose_name='Markdown Script'),
        ),
    ]
