# Generated by Django 3.2.5 on 2022-03-15 17:11

import content.validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20220311_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ytvideocontent',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='ytvideocontent',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='imagecontent',
            name='image',
            field=models.ImageField(help_text='Allowed extensions are: png, jpeg, jpg.', upload_to='uploads/contents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mdcontent',
            name='md',
            field=models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['md']), content.validator.Validator.validate_md], verbose_name='Markdown File'),
        ),
    ]
