# Generated by Django 3.2.5 on 2021-12-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20211201_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdcontent',
            name='html',
        ),
    ]
