# Generated by Django 3.0.7 on 2021-01-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20210105_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageattachment',
            options={'verbose_name': 'Image Attachment', 'verbose_name_plural': 'Image Attachments'},
        ),
        migrations.AlterField(
            model_name='pdfcontent',
            name='pdf',
            field=models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', verbose_name='Pdf'),
        ),
    ]
