# Generated by Django 3.0.7 on 2021-01-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20210105_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latex',
            name='textfield',
            field=models.TextField(verbose_name='Textfield'),
        ),
    ]
