# Generated by Django 3.2.20 on 2024-01-19 22:07

import content.mixin
import content.validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_display_name_required'),
        ('content', '0013_auto_20220315_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanoptoVideoContent',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.content', verbose_name='Content')),
                ('url', models.URLField(validators=[content.validator.Validator.validate_panopto_url], verbose_name='Video URL')),
            ],
            options={
                'verbose_name': 'Panopto Video Content',
                'verbose_name_plural': 'Panopto Video Contents',
            },
            bases=(models.Model, content.mixin.GeneratePreviewMixin),
        ),
    ]
