# Generated by Django 3.2.20 on 2024-02-06 17:13

import content.mixin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_course_moderators'),
        ('content', '0014_panoptovideocontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizContent',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.content', verbose_name='Content')),
                ('answers', models.ManyToManyField(related_name='quiz_answers', to='base.Content', verbose_name='Answers')),
                ('questions', models.ManyToManyField(related_name='quiz_questions', to='base.Content', verbose_name='Questions')),
            ],
            options={
                'verbose_name': 'Quiz Content',
                'verbose_name_plural': 'Quiz Contents',
            },
            bases=(models.Model, content.mixin.GeneratePreviewMixin),
        ),
    ]
