# Generated by Django 3.2.5 on 2022-01-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20220115_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytvideocontent',
            name='endTime',
            field=models.PositiveIntegerField(default=0, verbose_name='Video End Time in Seconds'),
        ),
    ]
