# Generated by Django 3.0.7 on 2021-01-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_imageattachment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleImageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/contents/%Y/%m/%d/', verbose_name='SingleImageAttachment')),
            ],
            options={
                'verbose_name': 'Single Image',
                'verbose_name_plural': 'Single Images',
            },
        ),
    ]
