# Generated by Django 3.0.7 on 2021-01-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_singleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageattachment',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, related_name='images', to='content.SingleImage', verbose_name='Images'),
        ),
    ]
