# Generated by Django 3.0.7 on 2021-01-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20210116_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleimageattachment',
            options={'verbose_name': 'Single Image Attachment', 'verbose_name_plural': 'Single Attachments'},
        ),
    ]
