# Generated by Django 3.2.20 on 2024-02-16 00:53

import content.mixin
import content.validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20240215_2344'),
        ('content', '0015_exercisecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnkiDeck',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.content', verbose_name='Content')),
                ('file', models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', validators=[content.validator.Validator.validate_anki_file], verbose_name='Anki Deck')),
                ('source', models.TextField(verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Anki Deck',
                'verbose_name_plural': 'Anki Decks',
            },
            bases=(models.Model, content.mixin.GeneratePreviewMixin),
        ),
    ]
