# Generated by Django 3.2.20 on 2024-02-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_course_moderators'),
        ('content', '0015_quizcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcontent',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='quiz_answers', to='base.Content', verbose_name='Answers'),
        ),
        migrations.AlterField(
            model_name='quizcontent',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quiz_questions', to='base.Content', verbose_name='Questions'),
        ),
    ]
