# Generated by Django 3.0.7 on 2021-01-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_imageattachment_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageattachment',
            name='license',
        ),
        migrations.RemoveField(
            model_name='imageattachment',
            name='source',
        ),
        migrations.AddField(
            model_name='singleimage',
            name='license',
            field=models.CharField(blank=True, max_length=200, verbose_name='License'),
        ),
        migrations.AddField(
            model_name='singleimage',
            name='source',
            field=models.TextField(default='easy_default', verbose_name='Source'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageattachment',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='content.SingleImageAttachment', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='singleimage',
            name='image',
            field=models.ImageField(upload_to='uploads/contents/%Y/%m/%d/', verbose_name='Attached Image'),
        ),
    ]
