# Generated by Django 3.2.20 on 2024-02-25 12:16

import content.mixin
import content.validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20240215_2344'),
        ('content', '0016_ankideck'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralURL',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.content', verbose_name='Content')),
                ('url', models.URLField(validators=[content.validator.Validator.validate_general_url], verbose_name='General URL')),
                ('title', models.TextField(verbose_name='The clear name of the site')),
            ],
            options={
                'verbose_name': 'General URL',
                'verbose_name_plural': 'General URLs',
            },
            bases=(models.Model, content.mixin.GeneratePreviewMixin),
        ),
    ]
