# Generated by Django 3.2.20 on 2024-02-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_course_moderators'),
        ('content', '0016_auto_20240206_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcontent',
            name='answers',
        ),
        migrations.CreateModel(
            name='BaseQuizQuestionAnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='base.content', verbose_name='Answers')),
                ('question', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='base.content', verbose_name='Questions')),
            ],
            options={
                'verbose_name': 'Quiz Question Answer Pair',
                'verbose_name_plural': 'Quiz Question Answer Pairs',
            },
        ),
        migrations.AlterField(
            model_name='quizcontent',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quiz_questions', to='content.BaseQuizQuestionAnswerModel', verbose_name='Questions'),
        ),
    ]
