# Generated by Django 3.2.20 on 2024-02-07 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20240206_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcontent',
            name='questions',
        ),
        migrations.AddField(
            model_name='quizcontent',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='content.basequizquestionanswermodel', verbose_name='Questions'),
        ),
    ]
