# Generated by Django 3.0.7 on 2021-01-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20210107_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleimage',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='uploads/contents/%Y/%m/%d/', verbose_name='Attached Image'),
        ),
    ]
