# Generated by Django 3.0.7 on 2021-01-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20210108_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleimage',
            name='image',
            field=models.ImageField(upload_to='uploads/contents/%Y/%m/%d/', verbose_name='Attached Image'),
        ),
    ]
