# Generated by Django 3.2.20 on 2024-02-07 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20240207_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Text Answer',
                'verbose_name_plural': 'Text Answers',
            },
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Text Question',
                'verbose_name_plural': 'Text Questions',
            },
        ),
        migrations.AddField(
            model_name='quizcontent',
            name='answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='content.textanswer', verbose_name='Answers'),
        ),
        migrations.AlterField(
            model_name='quizcontent',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='content.textquestion', verbose_name='Questions'),
        ),
        migrations.DeleteModel(
            name='BaseQuizQuestionAnswerModel',
        ),
    ]
