# Generated by Django 3.0.7 on 2021-01-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20210108_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfcontent',
            options={'verbose_name': 'PDF Content', 'verbose_name_plural': 'PDF Contents'},
        ),
        migrations.AlterField(
            model_name='latex',
            name='pdf',
            field=models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='latex',
            name='textfield',
            field=models.TextField(verbose_name='Latex Code'),
        ),
        migrations.AlterField(
            model_name='pdfcontent',
            name='pdf',
            field=models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='textfield',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
