# Generated by Django 3.2.20 on 2024-02-07 10:13

import content.mixin
import content.validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_course_moderators'),
        ('content', '0019_auto_20240207_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseContent',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.content', verbose_name='Content')),
                ('pdf', models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', validators=[content.validator.Validator.validate_pdf], verbose_name='PDF')),
                ('tasks', models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', validators=[content.validator.Validator.validate_pdf], verbose_name='Tasks')),
                ('solutions', models.FileField(blank=True, upload_to='uploads/contents/%Y/%m/%d/', validators=[content.validator.Validator.validate_pdf], verbose_name='Solutions')),
            ],
            options={
                'verbose_name': 'Exercise Content',
                'verbose_name_plural': 'Exercise Contents',
            },
            bases=(models.Model, content.mixin.GeneratePreviewMixin),
        ),
        migrations.DeleteModel(
            name='QuizContent',
        ),
        migrations.DeleteModel(
            name='TextAnswer',
        ),
        migrations.DeleteModel(
            name='TextQuestion',
        ),
    ]
