# Generated by Django 3.0.7 on 2021-01-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20210112_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleimage',
            name='image',
            field=models.ImageField(upload_to='uploads/contents/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
