# Generated by Django 3.2.20 on 2024-02-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20240207_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisecontent',
            name='pdf',
        ),
        migrations.AddField(
            model_name='exercisecontent',
            name='license',
            field=models.CharField(blank=True, max_length=200, verbose_name='License'),
        ),
        migrations.AddField(
            model_name='exercisecontent',
            name='source',
            field=models.TextField(default='', verbose_name='Source'),
            preserve_default=False,
        ),
    ]
