name: PyLint Django Parallel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7, 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pylint-django
          pip install -r requirements.txt
      - name: Run PyLint - base
        run: |
          pylint --fail-under=9 --load-plugins=pylint_django --django-settings-module=collab_coursebook.settings base
  content:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7, 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pylint-django
          pip install -r requirements.txt
      - name: Run PyLint - content
        run: |
          pylint --fail-under=9 --load-plugins=pylint_django --django-settings-module=collab_coursebook.settings content
  export:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7, 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pylint-django
          pip install -r requirements.txt
      - name: Run PyLint - export
        run: |
          pylint --fail-under=9 --load-plugins=pylint_django --django-settings-module=collab_coursebook.settings export

  frontend:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7, 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pylint-django
          pip install -r requirements.txt
      - name: Run PyLint - export
        run: |
          pylint --fail-under=9 --load-plugins=pylint_django --django-settings-module=collab_coursebook.settings frontend

    test:
      runs-on: ubuntu-latest
      strategy:
        max-parallel: 4
        matrix:
          python-version: [ 3.7, 3.8 ]
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v1
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install Python Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pylint
            pip install pylint-django
            pip install -r requirements.txt
        - name: Run PyLint - test
          run: |
            pylint --fail-under=9 --load-plugins=pylint_django --django-settings-module=collab_coursebook.settings test
          
